import = [
    "~/.config/alacritty/themes/themes/rose-pine.toml"
]

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
startup_mode = "Maximized"
